;# import corim.digest from rfcYYYY as corim
;# import eat.JC from rfc9711 as eat

measured-component = {
  id-label => component-id
  measurement
  ? signers-label => [ + signer-id-type ]
  ? flags-label => flags-type
}

measurement //= ( digested-measurement-label => corim.digest )
measurement //= ( raw-measurement-label => bytes )

signer-id-type = eat.JC<bytes-b64u, bytes>
flags-type = eat.JC<bytes8-b64u, bytes8>
